### ISSUE TITLE
is this project maintained?

### ISSUE THREAD

**Issue by efstathiosntonas** [cloudashdev/cloudash#103]
Is this project still maintained or it doesn't worth buying a subscription?

**Comment by mthenw** [comment]
@efstathiosntonas Hey! Yes it is. Though, I recognize we haven't released new version in a couple of months. Nevertheless we are working on some cool features.

**Comment by efstathiosntonas** [comment]
Thanks @mthenw! Keep it up!

**Comment by efstathiosntonas** [comment]
Hi @mthenw, it seems that maintenance has stopped long time ago. Are there any resurrection plans? If not, sorry but we will have to move to alternative solutions which is a pity since cloudash is really promising.

**Comment by aegixx** [comment]
@mthenw This is incredibly promising, but looks like you're no longer working on it. Is this something you could formally open source so folks can build on top of it?
