### ISSUE TITLE
[1.20.0] cannot click on top menu, cannot switch projects

### ISSUE THREAD

**Issue by efstathiosntonas** [cloudashdev/cloudash#105]
After upgrading to `1.20.0` I cannot click the projects on the top menu inside the app, (not the mac menus of the app)

![Screenshot 2023-08-28 at 13 16 57](https://github.com/cloudashdev/cloudash/assets/717975/c057d057-a785-4adf-9e82-38a5620a50e1)

edit: I think auto update should be disabled by default and allow the user to select if this setting should be switched on or off. It's really frustrating to have to reinstall 1.19.x after closing the app due to this issue.

**Comment by mthenw** [comment]
Sorry for that! We will have a bug today.

**Comment by efstathiosntonas** [comment]
thanks @mthenw !

**Comment by efstathiosntonas** [comment]
@mthenw forgot to mention that the menu button also doesn't work, not only the projects button, it seems like the entire row is disabled.

**Comment by mthenw** [comment]
The fix is on the way. New version will be released in ~30 minutes. Sorry for inconvenience.

**Comment by efstathiosntonas** [comment]
Perfect! No worries @mthenw, keep it up!

**Comment by efstathiosntonas** [comment]
fixed on https://github.com/cloudashdev/cloudash/releases/tag/1.20.1
