### ISSUE TITLE
Mac Apple Silicon (ARM64) build?

### ISSUE THREAD

**Issue by kopertop** [cloudashdev/cloudash#106]
Looks like there's only an Intel build published on the releases page. Are there any plans to build for Apple Silicon?

**Comment by mthenw** [comment]
We do have plans to release it. We are significantly refactoring the app right now but I will see if I can squeeze in publishing arm64 version.

**Comment by mthenw** [comment]
@kopertop we will start publishing ARM64 build starting from a new version that will be released on Monday.

**Comment by er-eis** [comment]
app runs on my M2 Max atm. Sonoma 14.0

**Comment by mthenw** [comment]
@kopertop we just released new version with ARM64 binaries. https://github.com/cloudashdev/cloudash/releases/tag/1.21.0
