### ISSUE TITLE
Assume role profiles in .aws/config not loaded

### ISSUE THREAD

**Issue by nathan-williams-rozettatechnology** [cloudashdev/cloudash#15]
In our organisation we have around 30 AWS accounts.
We have an "IAM" account where we use profiles to assume to roles in the other accounts.
These are defined in `~/.aws/config`

The only profile I can select in Cloudash is the profile with access keys defined in `~/.aws/credentials`

**Comment by mthenw** [comment]
That's correct. Right now Cloudash supports only profiles with credentials. MFA, SSO, and other variants will be supported in the upcoming versions.

**Comment by tommy31** [comment]
sadly same here... i'll wait for this feature. Thx app looks great

**Comment by mthenw** [comment]
This will supported with the next version.

**Comment by mthenw** [comment]
It will be released in the 0.3 version. I will publish it later today.

**Comment by mthenw** [comment]
@nathan-williams-rozettatechnology @tommy31 version 0.3 adds support for MFA and SSO profiles. You can download it here: https://github.com/cloudashdev/cloudash/releases/tag/0.3.0. Let me know if that works for you!
