### ISSUE TITLE
Window opens and spinner spins indefinitely.

### ISSUE THREAD

**Issue by mikeboehm** [cloudashdev/cloudash#20]
Window opens and spinner spins indefinitely.
I'm on Big Sur 11.1
Cloudash 0.3.0 and 0.3.1

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/208093/107724365-d2ab4280-6d37-11eb-9481-cbf02042d82f.png">

**Comment by mthenw** [comment]
Is it the first run or have you use it before?

**Comment by mikeboehm** [comment]
I've just now tried all the previous releases:
0.1.0 loads the form
0.2.0 and onwards shows the spinner

**Comment by mthenw** [comment]
Does it happen every time? You were able to see those errors, though https://github.com/cloudashdev/cloudash/issues/21

**Comment by mikeboehm** [comment]
Ah, sorry.
This ticket is trying to run it on my work computer (running Big Sur). The other ticket is Catalina

**Comment by mthenw** [comment]
This bug is caused by inability to read ~/.aws/config file. I added better error reporting in https://github.com/cloudashdev/cloudash/releases/tag/1.0.1.
