### ISSUE TITLE
The security token included in the request is invalid

### ISSUE THREAD

**Issue by mikeboehm** [cloudashdev/cloudash#21]
Cloudash 0.3.1
Catalina 10.15.7

In a browser, I login to our AWS using SSO and copy the credentials to ~/.aws/credentials.
The credentials in the file show up, but I get an error saying the token is invalid.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/208093/107865789-64dd5300-6ebe-11eb-970c-27f4e3d8689c.png"

**Comment by mthenw** [comment]
@mikeboehm thanks for reporting!

So you have a profile in `~/.aws/config` and under the same name you have credentials defined in `~/.aws/credentials`?

Can you list the fields (just field names, without values of course) that you define in the `~/.aws/credentials`?

**Comment by mthenw** [comment]
Hey, I fixed the issue. It will be released in 2-3 days.
