### ISSUE TITLE
Does not fetch list of stacks

### ISSUE THREAD

**Issue by serverlesspolska** [cloudashdev/cloudash#33]
I have an account with over 3000 CF stacks in the N.Virginia region. When selected application does not display anything and you can't go on.

I've been waiting several minutes when app was loading select box content, but eventually it does not display anything there
![image](https://user-images.githubusercontent.com/22025007/134004879-3f7bc1a8-7f98-4229-b783-3c6a4e32dc67.png)

**Comment by mthenw** [comment]
Hey @serverlesspolska thanks for reporting!

We will look into that!

**Comment by mthenw** [comment]
@serverlesspolska can you check again using the latest version https://github.com/cloudashdev/cloudash/releases/tag/1.0.3?

**Comment by serverlesspolska** [comment]
Unfortunately, I need to reopen it. 

In version 1.1.1 it worked well only once. It fetched a list of all stacks, and I was able to add the project. Alas, when trying to add another project from the same account + region, I got `Rate Exceeded` error.

I propose to cache fetched list of stacks. 
Also, allowing the user to paste stack name or id could be an option worth considering 🤔

**Comment by mthenw** [comment]
Thanks! We will look into it.

**Comment by mthenw** [comment]
@serverlesspolska can you try again with https://github.com/cloudashdev/cloudash/releases/tag/1.1.2?

**Comment by serverlesspolska** [comment]
@mthenw looks like the problem is gone. However, you still don't cache to first response. Fetching few thousands of CF stacks takes like 15-40 seconds, so it is a little annoying. 

Of course, most importantly, it works fine now. Thanks for fixing it :-)
