### ISSUE TITLE
Bug - not showing all functions on left hand side

### ISSUE THREAD

**Issue by mikebroberts** [cloudashdev/cloudash#36]
I have an app with 19 Lambda functions. Two of them aren't showing up on the left menu, but Cloudash definitely knows about at least one of them since I see metrics in the "5 most invoked functions" view

**Comment by mthenw** [comment]
Thanks for reporting @mikebroberts!

Any chances you could send us or paste here the CloudFormation stack template (of course without any sensitive date)? Do you use nested stacks there?

**Comment by mikebroberts** [comment]
One thing I just noticed - it's the last two **alphabetically in the stack* that are getting lost on the left hand side.

I'd rather not send the template - it's pretty long and it's going to be tough to clean that up to make public.

No nested stacks though - 19 functions plus other resources.

**Comment by bsb05** [comment]
@mthenw: Same issue last two functions are not shown in the left sidebar. CF stack has 24 lambda functions of which 22 are shown.

**Comment by bsb05** [comment]
@mthenw: FYI as per your message(https://github.com/cloudashdev/cloudash/issues/50#issuecomment-941659000) regarding left menu: `Note: if you will fold the left menu and hover over Lambda icon you will see the list of all functions`. When left menu is folded the missing last 2 functions are also shown which were hidden when the left menu was not folded.

**Comment by mthenw** [comment]
Fixed in https://github.com/cloudashdev/cloudash/releases/tag/1.2.1

**Comment by mikebroberts** [comment]
Thanks - I see the fix
