### ISSUE TITLE
Bug: log refresh issues

### ISSUE THREAD

**Issue by mikebroberts** [cloudashdev/cloudash#40]
Seeing various problems with logs being not refreshed, or being sorted oddly.

E.g. look at this 6 hour view - I'm seeing recent metrics, but the most recent log showing up at the top was 50 mins ago. I was also seeing weird things where clicking the refresh button was alternating what I'd see. And also I was just seeing stale data for an interval.

![image](https://user-images.githubusercontent.com/49635/134206413-8382038b-aa5d-451b-84b8-cbaeed4222c0.png)

**Comment by mthenw** [comment]
Thanks @mikebroberts for reporting! We will look into that.

**Comment by mthenw** [comment]
We changed how Cloudash fetches logs. It should be already fixed.
