### ISSUE TITLE
Be able to fold/unfold logs

### ISSUE THREAD

**Issue by Nicoowr** [cloudashdev/cloudash#42]
Hi,

Another thing which could be improved is to let the user reduce the size of big logs, like in Cloudwatch:

<img width="1315" alt="Screenshot 2021-09-23 at 10 23 54" src="https://user-images.githubusercontent.com/28652231/134475883-d6b166e8-2614-4860-b0d5-d78fe8a332ec.png">

Generally speaking, I believe there is a huge potential in Cloudash for debugging Serverless apps :)

**Comment by mthenw** [comment]
It will be released in the next version.
