### ISSUE TITLE
Can't move window by dragging menu bar

### ISSUE THREAD

**Issue by aidansteele** [cloudashdev/cloudash#49]
A typical behaviour on MacOS is being able to move an application window by dragging its menu bar. This works with Cloudash when it is backgrounded, but not when in the foreground. I have attached a video to demonstrate what I mean.

https://user-images.githubusercontent.com/369053/135179315-0df7f624-0dd4-40c9-bd75-b7cecf3ee923.mp4

**Comment by mthenw** [comment]
@aidansteele thanks for reporting. Which version do you run?
