### ISSUE TITLE
Resizable left menu

### ISSUE THREAD

**Issue by aidansteele** [cloudashdev/cloudash#50]
When I use SAM (example on left in screenshot), my list of function names is easy to read. When I use CDK (example on right) the function names are incomprehensible. I assume this is because you are rendering a name based on `aws:cloudformation:logical-id` and CDK generates those. Maybe you could 1) check for a `cloudash:name` tag and use that if available or 2) fallback to the logical ID.

Additionally, it could be useful to have the sidebar resizable for these very long logical IDs.

![CleanShot 2021-09-29 at 09 37 37@2x](https://user-images.githubusercontent.com/369053/135179730-436f60db-9c66-4bdd-b752-6332df507fba.png)

**Comment by mthenw** [comment]
@aidansteele thanks for reporting!

Would you prefer using tags or have an ability to rename function inside Cloudash?

**Comment by aidansteele** [comment]
I think I'd prefer tags. Because then I can use a CDK aspect to tag my functions with their "local" logical ID in my CDK stack

**Comment by moltar** [comment]
Another trick I used is to set descriptions to something more meaningful in CDK.

**Comment by bsb05** [comment]
@mthenw: Is it possible to have the left sidebar resizable as it is hard to find function when a CF stack has many functions with same prefix resulting in long function names? Thanks

Additionally, having a search option for function names in the left sidebar similar as profiles and stack selects(v1.2.0) would be very helpful for CF stack with many functions.

**Comment by mthenw** [comment]
Thank you all for the valuable feedback. Probably the best solution is to make the left menu resizable. 

Note: if you will fold the left menu and hover over Lambda icon you will see the list of all functions 

![image](https://user-images.githubusercontent.com/455261/137036740-842fdcbe-5347-4ad5-b0d4-2d245f44cbc8.png)

**Comment by mthenw** [comment]
Resolved in https://github.com/cloudashdev/cloudash/releases/tag/1.5.0
