### ISSUE TITLE
On-boarding process is confusing and not smooth

### ISSUE THREAD

**Issue by moltar** [cloudashdev/cloudash#54]
The process from the website landing to activation is not smooth and too many options.

On the website I have two choices (should be one path only):

1. Pay now
2. Download

It's not clear whether I can download & free trial it, or do I need to pay right away?

I decided to pay.

I paid.

All I got was an email Paddle with the "subscription purchase details".

When I launched Cloudash, it's asking for "Your license key", but I don't have one. I never got one from Paddle. I don't think it was on the thank you page either. I am now stuck and I have no idea what to do.

---

![screenshot-20211005T072450-nb0wQ1q9](https://user-images.githubusercontent.com/491247/135941777-953b3879-782f-42aa-9549-1f6b5fa5805d.png)

---

![screenshot-20211005T072507-QbXfkZxq](https://user-images.githubusercontent.com/491247/135941789-73d18c6c-0a6d-456c-8226-7b35c63a7685.png)

**Comment by moltar** [comment]
Ok, go the license key email but with a major delay (~ 30-40 minutes).

**Comment by mthenw** [comment]
Starting from the next version (1.15) Cloudash will not require license key to use it for 7 days.

**Comment by mthenw** [comment]
https://github.com/cloudashdev/cloudash/releases/tag/1.15.0
