### ISSUE TITLE
Grouping by CF stack is not useful

### ISSUE THREAD

**Issue by moltar** [cloudashdev/cloudash#55]
Our application consists of multiple stacks (6 for now, but will be 10 soon).

We deploy this application into several environments.

Adding each one of these as a separate service is very tedious.

**Comment by mthenw** [comment]
Support for manually picking AWS resources is already in the makings and planned for 1.16 release.

**Comment by mthenw** [comment]
Duplicate of https://github.com/cloudashdev/cloudash/issues/52. 

It will be released in the next release.
