### ISSUE TITLE
"Community Discussions" in Help menu redirects to atom.io

### ISSUE THREAD

**Issue by RafalWilinski** [cloudashdev/cloudash#59]
https://discuss.atom.io/c/electron
<img width="708" alt="Screenshot 2021-10-12 at 15 11 44" src="https://user-images.githubusercontent.com/3391616/136962590-f004a853-2d06-473a-bbf9-5c30747879c7.png">

**Comment by mthenw** [comment]
Fixed in https://github.com/cloudashdev/cloudash/releases/tag/1.2.1
