### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by tschoffelen** [cloudashdev/cloudash#64]
Excited to give Cloudash a try, but unfortunately after downloading I'm just getting a loading screen:

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/666220/139495474-16f88a87-7754-4165-82a9-d4abdd4bbbc3.png">

I'm on the latest version of macOS (`12.0.1 21A559`).

**Comment by mthenw** [comment]
@tschoffelen sorry for that. We will take a look at it. In the meantime, I will make sure to extend your trial period so you won't be charged until we fix this issue. Can you send us an email at hello@cloudash.dev?

**Comment by tschoffelen** [comment]
Thanks, will do. Let me know if there's anything I can do to help debug this issue.

**Comment by mthenw** [comment]
The bug has been fixed in https://github.com/cloudashdev/cloudash/releases/tag/1.3.1 :)
