### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by Rukenshia** [cloudashdev/cloudash#65]
Hi,

I've upgraded to 1.3.1, but when the application starts I can see a loading spinner for a fraction of a second, then the screen goes completely blank. Removing the app and re-adding it to my Applications folder did not change anything.

OS: macOS 11.6

**Comment by mthenw** [comment]
Thanks for reporting! We will look into that soon.

**Comment by mthenw** [comment]
@Rukenshia can you send me an email at maciej@cloudash.dev so we can debug it further?
