### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by brianfoody** [cloudashdev/cloudash#72]
Just authenticated and now I am no longer able to use the app. I tried upgrading and no luck with latest version (1.6.2)

<img width="520" alt="Screen Shot 2021-12-01 at 4 07 59 pm" src="https://user-images.githubusercontent.com/1926757/144269995-e701fa59-1f8c-406a-9d0a-375f2181c270.png">

**Comment by mthenw** [comment]
Hey @brianfoody, sorry for that. I'm investigating the issue.

**Comment by mthenw** [comment]
Looks like it might be related to the fact that you run Cloudash from outside /Applications folder. Could you move it there and try again?

**Comment by brianfoody** [comment]
Hey @mthenw , it's running from Applications folder. I tried deleting and reinstalling but still the same issue.

Is there a cache I can clear?

**Comment by mthenw** [comment]
The configuration file is stored in `/Users/<user>/Library/Application Support/Cloudash/config.json`. As a last resort you could try copying and deleting it.

**Comment by brianfoody** [comment]
Yep that did the trick! Weird stuff.
