### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by bahrmichael** [cloudashdev/cloudash#73]
> An unexpected error has occurred.

That's all the screen is showing. Version 1.6.2. It was working earlier today. I did not change AWS profiles. I used aws access keys as env vars on a terminal once.

Tried to reload, but just got a blank screen.

When I quit and restart I see a loading indicator for a second, and then it's back to "An unexpected error has occurred".

**Comment by mthenw** [comment]
Hey @bahrmichael, thanks for reporting. We will investigate it and get back to you.

**Comment by mthenw** [comment]
Can you try backing up the config file and remove it? The configuration file is stored in /Users/<user>/Library/Application Support/Cloudash/config.json. Then bringing it back and see if it works?

**Comment by bahrmichael** [comment]
Backed up the config with `mv config.json backup-config.json`.

Starting Cloudash then works fine and it asks me for the license key.

Restored the config with `mv backup-config.json config.json`.

Same error then happens again.

I backed up the config again, and copied the license key to create a new config. Workaround works for now. Do you want me to mail you my config so you can investigate that further?

**Comment by mthenw** [comment]
> I backed up the config again, and copied the license key to create a new config. Workaround works for now. Do you want me to mail you my config so you can investigate that further?

That would be perfect.
