### ISSUE TITLE
"An unexpected error occurred"

### ISSUE THREAD

**Issue by aidansteele** [cloudashdev/cloudash#74]
I just upgraded to Cloudash 1.6.2, went through the AWS SSO dance and now whenever I open the app it shows this. 

<img width="1481" alt="CleanShot 2022-01-18 at 14 01 58@2x" src="https://user-images.githubusercontent.com/369053/149863527-269a86b3-d908-41f1-bacc-70b3fa1c4ad5.png">

If I do View >> Reload then the message disappears but is still just an empty screen:

<img width="1481" alt="CleanShot 2022-01-18 at 14 03 01@2x" src="https://user-images.githubusercontent.com/369053/149863648-60edf27a-b322-4b65-a21f-a9ed9af12c9c.png">

Are there some caches that I should clear or something?

**Comment by aidansteele** [comment]
For what it's worth, I deleted my `~/Library/Application Support/cloudash`, re-entered my licence key, set up my app again and it works now. But that means I might not be able to help with debugging this 😅

**Comment by mthenw** [comment]
Thanks for reporting. It's a known bug that happens from time to time. I will investigate it today.

**Comment by mthenw** [comment]
Should be fixed with the latest release.
