### ISSUE TITLE
Bug: unable to view logs through API routes screen

### ISSUE THREAD

**Issue by aidansteele** [cloudashdev/cloudash#77]
My API GW route integrations use a Lambda function with an alias. This causes log-fetching to fail because the alias should be stripped from the log group name. See screenshot for clearer explanation

![CleanShot 2022-03-01 at 10 12 11@2x](https://user-images.githubusercontent.com/369053/156074451-e407bcf6-28bf-450d-9bf6-b2d5c80ced8c.png)

**Comment by mthenw** [comment]
Thanks for reporting. It will be fix in the next release.

**Comment by mthenw** [comment]
Fixed in https://github.com/cloudashdev/cloudash/releases/tag/1.9.1
