### ISSUE TITLE
Support for showing all CloudWatch Log Groups

### ISSUE THREAD

**Issue by rogerchi** [cloudashdev/cloudash#81]
We have a number of APIs which use express synchronous step functions integrations, would be great to get those logs in this tool as well.

**Comment by mthenw** [comment]
I think we may start supporting CW log groups as individual resources in Cloudash.

**Comment by mthenw** [comment]
Support for showing all Log Groups from a CF stack will be released in the next version.

**Comment by mthenw** [comment]
Added in https://github.com/cloudashdev/cloudash/releases/tag/1.15.0
