### ISSUE TITLE
CloudWatch filter syntax cheatsheet

### ISSUE THREAD

**Issue by tlakomy** [cloudashdev/cloudash#84]
Currently searching for `request-id-123-something` returns an empty list and customers need to wrap their requestID/xRayTraceId/whatever in `""` which is quite confusing.

**Comment by mthenw** [comment]
In the next version we will start showing a hint that a search query should be wrapped with `""`. But I think ultimately we should show a CloudWatch filter syntax cheatsheet somewhere in the app.
