### ISSUE TITLE
Feature Request: Add option to disable auto-update

### ISSUE THREAD

**Issue by apburgess** [cloudashdev/cloudash#86]
I keep having issues with the latest release launching to an empty window with the activity spinner, but because of the auto-update downgrading only works until I quit.  Having the option to disable the auto-update process (but still being notified) would be great.

**Comment by mthenw** [comment]
Thanks for reporting and sorry for inconvenience. I think the crucial part here is to solve the core issue of the empty screen. We are looking in to that issue. I will keep you updated.

**Comment by mthenw** [comment]
We found the issue. New version will be released in about 20 minutes.

**Comment by mthenw** [comment]
Regarding the original feature request. I think that disabling auto-update is a bad pattern and we would like to avoid it. Nevertheless, we will improve our test suite to make sure we won't release new versions with major bugs like this one.

**Comment by mthenw** [comment]
Can you try https://github.com/cloudashdev/cloudash/releases/tag/1.14.1 and let me know if it works?
