### ISSUE TITLE
Bug: Latest versions don't show anything when opening

### ISSUE THREAD

**Issue by rogerchi** [cloudashdev/cloudash#87]
I installed the latest version of CloudAsh on my M1 Macbook Pro (no prior installation of CloudAsh) and upon loading, no onboarding window shows and no menu options allow me to open a window or input my license key.  I downloaded an old version (1.11.0) which then gave me the window the input my license key and then upon updating again to the latest version everything works.

**Comment by mthenw** [comment]
Thanks for reporting and sorry for inconvenience. We are looking into that.

**Comment by mthenw** [comment]
We found the issue. New version will be released in about 20 minutes.

**Comment by mthenw** [comment]
Can you try https://github.com/cloudashdev/cloudash/releases/tag/1.14.1 and let me know if it works?

**Comment by rogerchi** [comment]
Looks like it works now (I moved Cloudash to the trash, then deleted the ~/Library references to the application and reinstalled)

**Comment by apburgess** [comment]
I'm still seeing the issue if I quit and relaunch the latest version a few times.

**Comment by mthenw** [comment]
@apburgess could you send me an email at maciej@cloudash.dev. We will followup there as I would have to ask you to send us your config.
