### ISSUE TITLE
Unable to add Serverless Framework Stack

### ISSUE THREAD

**Issue by nason** [cloudashdev/cloudash#88]
I'm just getting set up with Clouddash, its a great tool!

Unfortunately, I get an error when adding certain stacks:

> Unable to fetch stack resources
> Cannot read properties of undefined (reading 'split')

I have added other stacks in the same account/region without this issue. 

Do you have any insight as to why I'd be getting this error, or if there is anything I can do to avoid it?

**Comment by mthenw** [comment]
Thanks for reporting! What kind of deployment tool do you use?

**Comment by nason** [comment]
We use CDK and serverless framework. I've added stacks from both fine, but a few serverless framework ones are giving me this error.

**Comment by mthenw** [comment]
@nason which version of the serverless framework do you use? Any chance you could share your serverless.yaml of the failing stack? Can be via mail maciej@cloudash.dev

**Comment by mthenw** [comment]
This should be fixed in the current version.
