### ISSUE TITLE
Cloudash stucked at loading screen

### ISSUE THREAD

**Issue by leopinzon** [cloudashdev/cloudash#92]
I downloaded the Version 1.14.2 (1.14.2) but it won't pass from the loading screen. 
System info: Macos Monterey 12.3.1

**Comment by mthenw** [comment]
Hello @leopinzon,

sorry for the inconvenience. Is it the first time you run Cloudash or did you run any earlier versions? Does the loading screen happen after providing the license key or you weren't even able to provide it?

**Comment by mthenw** [comment]
Closing for now as no reply. Please let me know if that's still an issue.
