### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by silvexis** [cloudashdev/cloudash#99]
If you live long enough, there comes a time in every product's life that someone eventually asks for dark mode.

That day is today. My eyes thank you in advance.

**Comment by mthenw** [comment]
Will do, will do...

**Comment by mthenw** [comment]
@silvexis I'm happy to announce the we released Dark Mode in the https://github.com/cloudashdev/cloudash/releases/tag/1.19.0 version. 

Just run Cloudash and it will auto update.
